name: my_workspace

packages:
  - packages/**

scripts:
  build:runner:
    run: melos exec -c 1 -- flutter pub run build_runner build --delete-conflicting-outputs

  clean:
    run: melos exec -- flutter clean

  analyze:
    run: melos exec -- flutter analyze


# [   melos run build:runner   ] : build runner 실행
# [   melos run clean   ] : 클린 실행
# [   melos run analyze   ] : 분석 실행
# [   melos bootstrap   ] : 부트스트랩 실행 (pub get 실행)
# [   melos exec --scope=data -- flutter pub run build_runner build   ] : data 범위에서 build runner 실행
# [   melos exec -- flutter test   ] : 테스트 실행
