name: flutter_ui
description: "UI PoC For Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  data:
    path: ./packages/data
  domain:
    path: ./packages/domain
  presentation:
    path: ./packages/presentation

dev_dependencies:
  flutter_test:
    sdk: flutter

  # auto generate 등을 위한 빌드 세팅
  build_runner: ^2.4.12
  melos: ^6.3.2

  # 라우팅 라이브러리
  go_router: ^15.1.2

  # 의존성 주입 라이브러리
  get_it: ^8.0.3

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
